### ISSUE TITLE
API Post Check-in

### ISSUE THREAD

**Issue by smarbaf** [treemoapp/treemo-web#8]
As a mobile developer
I want an API that allows me to post a check-in
So that I can keep a log of check-ins for that location

Given a location 'Trade' with id 1
And a user id 20
When I send a POST request to /check-ins
With parameters user id and location id
Then check-in is logged in database
And 201 response is returned

**Comment by rodcul** [comment]
- Model check-ins
- Relationship belongs to/has many users + locations
- Process post request with parameters
